Nom: UHC_Scenarios
principal: SmarTechMCPE\Main
api: 2.0.0
version: 2.2.2.invisible
author: SmarTech MCPE
commands:
 uhc:
  descriptions: 
  permission: uhc.cmd
permissions:
  UHC.group.Host:
    default: false
  UHC.group.Owner:
    default: false
  UHC.group.Admin:
    default: false
  UHC.group.Mod:
    default: false
  UHC.group.Dev:
    default: false
  UHC.group.Trainee:
    default: false
  UHC.group.Helper:
    default: false
  UHC.group.YouTube:
    default: false
